create table coches (
	id INT,
	marca VARCHAR(50),
	modelo VARCHAR(50),
	pais VARCHAR(50)
);
insert into coches (id, marca, modelo, pais) values (1, 'Mercedes-Benz', '300E', 'Finland');
insert into coches (id, marca, modelo, pais) values (2, 'Mercury', 'Monterey', 'Argentina');
insert into coches (id, marca, modelo, pais) values (3, 'Plymouth', 'Reliant', 'Japan');
insert into coches (id, marca, modelo, pais) values (4, 'Mitsubishi', 'Montero', 'Angola');
insert into coches (id, marca, modelo, pais) values (5, 'Suzuki', 'Reno', 'Portugal');
insert into coches (id, marca, modelo, pais) values (6, 'Audi', 'S4', 'Peru');
insert into coches (id, marca, modelo, pais) values (7, 'Lamborghini', 'Murciélago', 'Sweden');
insert into coches (id, marca, modelo, pais) values (8, 'Porsche', '944', 'Portugal');
insert into coches (id, marca, modelo, pais) values (9, 'Mitsubishi', 'Cordia', 'United Kingdom');
insert into coches (id, marca, modelo, pais) values (10, 'Mercury', 'Topaz', 'Argentina');
insert into coches (id, marca, modelo, pais) values (11, 'Jeep', 'Wrangler', 'Burkina Faso');
insert into coches (id, marca, modelo, pais) values (12, 'Land Rover', 'Range Rover Sport', 'Sweden');
insert into coches (id, marca, modelo, pais) values (13, 'Mercury', 'Milan', 'Russia');
insert into coches (id, marca, modelo, pais) values (14, 'Bentley', 'Brooklands', 'Portugal');
insert into coches (id, marca, modelo, pais) values (15, 'Daewoo', 'Nubira', 'Poland');
insert into coches (id, marca, modelo, pais) values (16, 'Buick', 'Reatta', 'China');
insert into coches (id, marca, modelo, pais) values (17, 'Honda', 'Prelude', 'Portugal');
insert into coches (id, marca, modelo, pais) values (18, 'GMC', 'Sierra 2500', 'China');
insert into coches (id, marca, modelo, pais) values (19, 'Mazda', 'MPV', 'Colombia');
insert into coches (id, marca, modelo, pais) values (20, 'Toyota', 'Tercel', 'China');
insert into coches (id, marca, modelo, pais) values (21, 'Daewoo', 'Leganza', 'Dominican Republic');
insert into coches (id, marca, modelo, pais) values (22, 'Dodge', 'Grand Caravan', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (23, 'Buick', 'Coachbuilder', 'Thailand');
insert into coches (id, marca, modelo, pais) values (24, 'Chevrolet', 'Cavalier', 'China');
insert into coches (id, marca, modelo, pais) values (25, 'Mazda', 'RX-7', 'Poland');
insert into coches (id, marca, modelo, pais) values (26, 'GMC', '1500', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (27, 'Audi', 'S4', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (28, 'Buick', 'Century', 'Croatia');
insert into coches (id, marca, modelo, pais) values (29, 'GMC', '2500', 'France');
insert into coches (id, marca, modelo, pais) values (30, 'Subaru', 'Brat', 'Netherlands');
insert into coches (id, marca, modelo, pais) values (31, 'GMC', 'Canyon', 'Peru');
insert into coches (id, marca, modelo, pais) values (32, 'Ford', 'EXP', 'Japan');
insert into coches (id, marca, modelo, pais) values (33, 'BMW', '8 Series', 'Russia');
insert into coches (id, marca, modelo, pais) values (34, 'Jeep', 'Grand Cherokee', 'Philippines');
insert into coches (id, marca, modelo, pais) values (35, 'Pontiac', 'Firebird Trans Am', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (36, 'Mitsubishi', 'Precis', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (37, 'Chevrolet', 'Camaro', 'Ukraine');
insert into coches (id, marca, modelo, pais) values (38, 'Hyundai', 'Sonata', 'Brazil');
insert into coches (id, marca, modelo, pais) values (39, 'Acura', 'RL', 'Sweden');
insert into coches (id, marca, modelo, pais) values (40, 'Acura', 'RL', 'France');
insert into coches (id, marca, modelo, pais) values (41, 'Toyota', 'Avalon', 'Vietnam');
insert into coches (id, marca, modelo, pais) values (42, 'Dodge', 'Ram 1500', 'China');
insert into coches (id, marca, modelo, pais) values (43, 'Mitsubishi', 'Tredia', 'Japan');
insert into coches (id, marca, modelo, pais) values (44, 'Mercedes-Benz', 'S-Class', 'United States');
insert into coches (id, marca, modelo, pais) values (45, 'Pontiac', 'Parisienne', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (46, 'Cadillac', 'Fleetwood', 'Ukraine');
insert into coches (id, marca, modelo, pais) values (47, 'Ford', 'Bronco', 'China');
insert into coches (id, marca, modelo, pais) values (48, 'Chevrolet', 'Monte Carlo', 'Venezuela');
insert into coches (id, marca, modelo, pais) values (49, 'Honda', 'Accord', 'Denmark');
insert into coches (id, marca, modelo, pais) values (50, 'Infiniti', 'FX', 'Ukraine');
insert into coches (id, marca, modelo, pais) values (51, 'Toyota', 'Celica', 'Philippines');
insert into coches (id, marca, modelo, pais) values (52, 'Plymouth', 'Laser', 'Pakistan');
insert into coches (id, marca, modelo, pais) values (53, 'Mercury', 'Cougar', 'Ethiopia');
insert into coches (id, marca, modelo, pais) values (54, 'Ford', 'Falcon', 'China');
insert into coches (id, marca, modelo, pais) values (55, 'Kia', 'Rio', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (56, 'Ford', 'Econoline E150', 'Syria');
insert into coches (id, marca, modelo, pais) values (57, 'Volvo', '940', 'China');
insert into coches (id, marca, modelo, pais) values (58, 'Saturn', 'Aura', 'Greece');
insert into coches (id, marca, modelo, pais) values (59, 'Hyundai', 'Tucson', 'United States');
insert into coches (id, marca, modelo, pais) values (60, 'Chevrolet', 'Suburban 1500', 'Palestinian Territory');
insert into coches (id, marca, modelo, pais) values (61, 'Chevrolet', 'G-Series 1500', 'Madagascar');
insert into coches (id, marca, modelo, pais) values (62, 'Mitsubishi', 'Galant', 'Burkina Faso');
insert into coches (id, marca, modelo, pais) values (63, 'Volvo', 'S80', 'Philippines');
insert into coches (id, marca, modelo, pais) values (64, 'Honda', 'Pilot', 'Maldives');
insert into coches (id, marca, modelo, pais) values (65, 'Lamborghini', 'Diablo', 'China');
insert into coches (id, marca, modelo, pais) values (66, 'Hummer', 'H2', 'Russia');
insert into coches (id, marca, modelo, pais) values (67, 'Saturn', 'VUE', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (68, 'Lamborghini', 'Diablo', 'Uruguay');
insert into coches (id, marca, modelo, pais) values (69, 'Audi', 'R8', 'Poland');
insert into coches (id, marca, modelo, pais) values (70, 'Mercedes-Benz', 'SL-Class', 'Afghanistan');
insert into coches (id, marca, modelo, pais) values (71, 'Maybach', 'Landaulet', 'Poland');
insert into coches (id, marca, modelo, pais) values (72, 'Mazda', 'Mazda5', 'Honduras');
insert into coches (id, marca, modelo, pais) values (73, 'Mazda', 'MX-3', 'Mexico');
insert into coches (id, marca, modelo, pais) values (74, 'Spyker', 'C8', 'China');
insert into coches (id, marca, modelo, pais) values (75, 'BMW', 'X5', 'United States');
insert into coches (id, marca, modelo, pais) values (76, 'Chevrolet', 'Malibu Maxx', 'Italy');
insert into coches (id, marca, modelo, pais) values (77, 'Mitsubishi', 'GTO', 'Peru');
insert into coches (id, marca, modelo, pais) values (78, 'Suzuki', 'Swift', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (79, 'Volkswagen', 'Jetta', 'China');
insert into coches (id, marca, modelo, pais) values (80, 'Suzuki', 'Verona', 'Ecuador');
insert into coches (id, marca, modelo, pais) values (81, 'GMC', 'Jimmy', 'Russia');
insert into coches (id, marca, modelo, pais) values (82, 'Nissan', 'Murano', 'Poland');
insert into coches (id, marca, modelo, pais) values (83, 'Dodge', 'Ram Van B250', 'China');
insert into coches (id, marca, modelo, pais) values (84, 'Nissan', 'NX', 'Uganda');
insert into coches (id, marca, modelo, pais) values (85, 'Audi', 'A4', 'Guatemala');
insert into coches (id, marca, modelo, pais) values (86, 'Suzuki', 'Daewoo Lacetti', 'China');
insert into coches (id, marca, modelo, pais) values (87, 'Mitsubishi', 'Challenger', 'Russia');
insert into coches (id, marca, modelo, pais) values (88, 'Chevrolet', 'Suburban', 'Ukraine');
insert into coches (id, marca, modelo, pais) values (89, 'Hyundai', 'Sonata', 'Nigeria');
insert into coches (id, marca, modelo, pais) values (90, 'Ford', 'Crown Victoria', 'Poland');
insert into coches (id, marca, modelo, pais) values (91, 'BMW', '6 Series', 'Mexico');
insert into coches (id, marca, modelo, pais) values (92, 'Mazda', '626', 'Sweden');
insert into coches (id, marca, modelo, pais) values (93, 'Ram', '3500', 'Poland');
insert into coches (id, marca, modelo, pais) values (94, 'BMW', 'M Roadster', 'China');
insert into coches (id, marca, modelo, pais) values (95, 'Ford', 'Ranger', 'Sweden');
insert into coches (id, marca, modelo, pais) values (96, 'Volkswagen', 'GTI', 'Russia');
insert into coches (id, marca, modelo, pais) values (97, 'Nissan', 'Xterra', 'China');
insert into coches (id, marca, modelo, pais) values (98, 'Maybach', '57', 'China');
insert into coches (id, marca, modelo, pais) values (99, 'Jeep', 'Patriot', 'Brazil');
insert into coches (id, marca, modelo, pais) values (100, 'Mercedes-Benz', 'S-Class', 'Ecuador');
insert into coches (id, marca, modelo, pais) values (101, 'Mazda', 'Miata MX-5', 'Peru');
insert into coches (id, marca, modelo, pais) values (102, 'Mazda', 'RX-8', 'Portugal');
insert into coches (id, marca, modelo, pais) values (103, 'Nissan', 'Versa', 'China');
insert into coches (id, marca, modelo, pais) values (104, 'Lexus', 'LX', 'Japan');
insert into coches (id, marca, modelo, pais) values (105, 'Ford', 'Festiva', 'Philippines');
insert into coches (id, marca, modelo, pais) values (106, 'Audi', '100', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (107, 'Smart', 'Fortwo', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (108, 'Plymouth', 'Neon', 'Chile');
insert into coches (id, marca, modelo, pais) values (109, 'Acura', 'NSX', 'France');
insert into coches (id, marca, modelo, pais) values (110, 'Dodge', 'Durango', 'Dominican Republic');
insert into coches (id, marca, modelo, pais) values (111, 'Toyota', 'T100 Xtra', 'China');
insert into coches (id, marca, modelo, pais) values (112, 'Toyota', '4Runner', 'Canada');
insert into coches (id, marca, modelo, pais) values (113, 'Mazda', '929', 'China');
insert into coches (id, marca, modelo, pais) values (114, 'Mazda', 'CX-9', 'Kosovo');
insert into coches (id, marca, modelo, pais) values (115, 'Maserati', 'GranTurismo', 'China');
insert into coches (id, marca, modelo, pais) values (116, 'Pontiac', 'Tempest', 'Malaysia');
insert into coches (id, marca, modelo, pais) values (117, 'Chevrolet', 'Express 1500', 'Vietnam');
insert into coches (id, marca, modelo, pais) values (118, 'Dodge', 'Neon', 'Finland');
insert into coches (id, marca, modelo, pais) values (119, 'Nissan', 'Frontier', 'France');
insert into coches (id, marca, modelo, pais) values (120, 'Land Rover', 'Range Rover Sport', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (121, 'Subaru', 'Legacy', 'Serbia');
insert into coches (id, marca, modelo, pais) values (122, 'Audi', 'S4', 'North Korea');
insert into coches (id, marca, modelo, pais) values (123, 'Chevrolet', 'Colorado', 'Poland');
insert into coches (id, marca, modelo, pais) values (124, 'Mercury', 'Grand Marquis', 'Myanmar');
insert into coches (id, marca, modelo, pais) values (125, 'Toyota', 'MR2', 'United States');
insert into coches (id, marca, modelo, pais) values (126, 'Nissan', 'Frontier', 'France');
insert into coches (id, marca, modelo, pais) values (127, 'Ford', 'E-Series', 'Madagascar');
insert into coches (id, marca, modelo, pais) values (128, 'Honda', 'Fit', 'Ireland');
insert into coches (id, marca, modelo, pais) values (129, 'Toyota', 'Avalon', 'Portugal');
insert into coches (id, marca, modelo, pais) values (130, 'Volkswagen', 'Jetta', 'Japan');
insert into coches (id, marca, modelo, pais) values (131, 'Toyota', 'Camry', 'China');
insert into coches (id, marca, modelo, pais) values (132, 'Hyundai', 'Tiburon', 'Iran');
insert into coches (id, marca, modelo, pais) values (133, 'BMW', '645', 'Tunisia');
insert into coches (id, marca, modelo, pais) values (134, 'Cadillac', 'CTS-V', 'Philippines');
insert into coches (id, marca, modelo, pais) values (135, 'GMC', 'Sierra', 'Costa Rica');
insert into coches (id, marca, modelo, pais) values (136, 'Toyota', '4Runner', 'Philippines');
insert into coches (id, marca, modelo, pais) values (137, 'Dodge', 'Journey', 'Russia');
insert into coches (id, marca, modelo, pais) values (138, 'Subaru', 'Legacy', 'Sierra Leone');
insert into coches (id, marca, modelo, pais) values (139, 'Ford', 'E150', 'China');
insert into coches (id, marca, modelo, pais) values (140, 'Toyota', 'RAV4', 'Japan');
insert into coches (id, marca, modelo, pais) values (141, 'Dodge', 'Durango', 'Belarus');
insert into coches (id, marca, modelo, pais) values (142, 'Buick', 'Rendezvous', 'Poland');
insert into coches (id, marca, modelo, pais) values (143, 'Volkswagen', 'Passat', 'China');
insert into coches (id, marca, modelo, pais) values (144, 'Pontiac', 'GTO', 'Thailand');
insert into coches (id, marca, modelo, pais) values (145, 'Jaguar', 'XJ Series', 'Dominican Republic');
insert into coches (id, marca, modelo, pais) values (146, 'Porsche', 'Boxster', 'Poland');
insert into coches (id, marca, modelo, pais) values (147, 'Geo', 'Prizm', 'Croatia');
insert into coches (id, marca, modelo, pais) values (148, 'Volkswagen', 'Passat', 'Poland');
insert into coches (id, marca, modelo, pais) values (149, 'Chevrolet', 'Avalanche 2500', 'Honduras');
insert into coches (id, marca, modelo, pais) values (150, 'Chevrolet', 'Camaro', 'Greece');
insert into coches (id, marca, modelo, pais) values (151, 'BMW', 'X6', 'Vietnam');
insert into coches (id, marca, modelo, pais) values (152, 'Ford', 'LTD Crown Victoria', 'Israel');
insert into coches (id, marca, modelo, pais) values (153, 'Chrysler', 'Cirrus', 'China');
insert into coches (id, marca, modelo, pais) values (154, 'Toyota', 'Matrix', 'Morocco');
insert into coches (id, marca, modelo, pais) values (155, 'BMW', 'M5', 'China');
insert into coches (id, marca, modelo, pais) values (156, 'GMC', 'Envoy XUV', 'Pakistan');
insert into coches (id, marca, modelo, pais) values (157, 'Dodge', 'Ram Wagon B350', 'Philippines');
insert into coches (id, marca, modelo, pais) values (158, 'Chevrolet', 'Avalanche', 'Portugal');
insert into coches (id, marca, modelo, pais) values (159, 'Lamborghini', 'Gallardo', 'Philippines');
insert into coches (id, marca, modelo, pais) values (160, 'Chevrolet', 'Corvette', 'Madagascar');
insert into coches (id, marca, modelo, pais) values (161, 'Volkswagen', 'GTI', 'Portugal');
insert into coches (id, marca, modelo, pais) values (162, 'Cadillac', 'CTS', 'Philippines');
insert into coches (id, marca, modelo, pais) values (163, 'Ford', 'Edge', 'Colombia');
insert into coches (id, marca, modelo, pais) values (164, 'Eagle', 'Vision', 'Brazil');
insert into coches (id, marca, modelo, pais) values (165, 'Chrysler', 'Town & Country', 'Russia');
insert into coches (id, marca, modelo, pais) values (166, 'GMC', 'Sierra 2500', 'Argentina');
insert into coches (id, marca, modelo, pais) values (167, 'Suzuki', 'Reno', 'Thailand');
insert into coches (id, marca, modelo, pais) values (168, 'Subaru', 'Outback', 'Nigeria');
insert into coches (id, marca, modelo, pais) values (169, 'Ford', 'F450', 'Philippines');
insert into coches (id, marca, modelo, pais) values (170, 'Lexus', 'LS', 'Philippines');
insert into coches (id, marca, modelo, pais) values (171, 'Ferrari', '458 Italia', 'China');
insert into coches (id, marca, modelo, pais) values (172, 'Hyundai', 'Accent', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (173, 'Chevrolet', 'Caprice', 'Philippines');
insert into coches (id, marca, modelo, pais) values (174, 'Honda', 'Ridgeline', 'China');
insert into coches (id, marca, modelo, pais) values (175, 'Volvo', 'S60', 'Portugal');
insert into coches (id, marca, modelo, pais) values (176, 'Plymouth', 'Neon', 'Serbia');
insert into coches (id, marca, modelo, pais) values (177, 'Chevrolet', 'Avalanche 1500', 'Argentina');
insert into coches (id, marca, modelo, pais) values (178, 'Pontiac', 'Montana SV6', 'Macedonia');
insert into coches (id, marca, modelo, pais) values (179, 'Audi', 'riolet', 'Peru');
insert into coches (id, marca, modelo, pais) values (180, 'Buick', 'Reatta', 'Russia');
insert into coches (id, marca, modelo, pais) values (181, 'Chevrolet', 'Astro', 'Sweden');
insert into coches (id, marca, modelo, pais) values (182, 'Ford', 'F150', 'Serbia');
insert into coches (id, marca, modelo, pais) values (183, 'Dodge', 'Ram 1500', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (184, 'Volkswagen', 'CC', 'China');
insert into coches (id, marca, modelo, pais) values (185, 'Audi', 'TT', 'Brazil');
insert into coches (id, marca, modelo, pais) values (186, 'Buick', 'Regal', 'Mexico');
insert into coches (id, marca, modelo, pais) values (187, 'Chevrolet', 'Silverado 1500', 'France');
insert into coches (id, marca, modelo, pais) values (188, 'Toyota', 'Sienna', 'Philippines');
insert into coches (id, marca, modelo, pais) values (189, 'GMC', 'Jimmy', 'China');
insert into coches (id, marca, modelo, pais) values (190, 'Chevrolet', 'Express 1500', 'Panama');
insert into coches (id, marca, modelo, pais) values (191, 'Volvo', '960', 'Russia');
insert into coches (id, marca, modelo, pais) values (192, 'Saab', '9-5', 'Peru');
insert into coches (id, marca, modelo, pais) values (193, 'GMC', 'Sierra 1500', 'Finland');
insert into coches (id, marca, modelo, pais) values (194, 'Ford', 'Edge', 'China');
insert into coches (id, marca, modelo, pais) values (195, 'Mitsubishi', 'Sigma', 'Mexico');
insert into coches (id, marca, modelo, pais) values (196, 'Lincoln', 'Continental', 'Bosnia and Herzegovina');
insert into coches (id, marca, modelo, pais) values (197, 'Jeep', 'Wrangler', 'South Africa');
insert into coches (id, marca, modelo, pais) values (198, 'Buick', 'Century', 'Argentina');
insert into coches (id, marca, modelo, pais) values (199, 'Toyota', 'MR2', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (200, 'Alfa Romeo', 'Spider', 'Peru');
insert into coches (id, marca, modelo, pais) values (201, 'Chrysler', 'Town & Country', 'France');
insert into coches (id, marca, modelo, pais) values (202, 'Land Rover', 'Discovery', 'Australia');
insert into coches (id, marca, modelo, pais) values (203, 'Mercedes-Benz', 'S-Class', 'Philippines');
insert into coches (id, marca, modelo, pais) values (204, 'Ford', 'Crown Victoria', 'China');
insert into coches (id, marca, modelo, pais) values (205, 'Land Rover', 'Discovery', 'France');
insert into coches (id, marca, modelo, pais) values (206, 'Ford', 'Expedition', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (207, 'Audi', 'Q5', 'China');
insert into coches (id, marca, modelo, pais) values (208, 'Mazda', 'Navajo', 'Ukraine');
insert into coches (id, marca, modelo, pais) values (209, 'BMW', '8 Series', 'Venezuela');
insert into coches (id, marca, modelo, pais) values (210, 'Ford', 'Windstar', 'Sweden');
insert into coches (id, marca, modelo, pais) values (211, 'Jaguar', 'XJ', 'Papua New Guinea');
insert into coches (id, marca, modelo, pais) values (212, 'Suzuki', 'Esteem', 'Azerbaijan');
insert into coches (id, marca, modelo, pais) values (213, 'Volkswagen', 'Jetta', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (214, 'Ford', 'Mustang', 'Finland');
insert into coches (id, marca, modelo, pais) values (215, 'Lexus', 'GX', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (216, 'Lincoln', 'Town Car', 'Poland');
insert into coches (id, marca, modelo, pais) values (217, 'Hyundai', 'Accent', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (218, 'Mazda', 'RX-7', 'Honduras');
insert into coches (id, marca, modelo, pais) values (219, 'Volvo', 'S80', 'France');
insert into coches (id, marca, modelo, pais) values (220, 'Jaguar', 'XK Series', 'Jamaica');
insert into coches (id, marca, modelo, pais) values (221, 'Porsche', 'Cayman', 'China');
insert into coches (id, marca, modelo, pais) values (222, 'Pontiac', 'Grand Prix', 'Germany');
insert into coches (id, marca, modelo, pais) values (223, 'Lexus', 'IS F', 'Philippines');
insert into coches (id, marca, modelo, pais) values (224, 'Buick', 'LaCrosse', 'Armenia');
insert into coches (id, marca, modelo, pais) values (225, 'Plymouth', 'Prowler', 'Ivory Coast');
insert into coches (id, marca, modelo, pais) values (226, 'Maserati', 'Karif', 'Canada');
insert into coches (id, marca, modelo, pais) values (227, 'Mazda', '929', 'China');
insert into coches (id, marca, modelo, pais) values (228, 'Ram', 'Dakota', 'Macedonia');
insert into coches (id, marca, modelo, pais) values (229, 'GMC', 'Sonoma Club Coupe', 'Finland');
insert into coches (id, marca, modelo, pais) values (230, 'Acura', 'Integra', 'Peru');
insert into coches (id, marca, modelo, pais) values (231, 'Pontiac', 'Grand Am', 'Mali');
insert into coches (id, marca, modelo, pais) values (232, 'Saturn', 'S-Series', 'Mongolia');
insert into coches (id, marca, modelo, pais) values (233, 'Ford', 'Probe', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (234, 'Ford', 'Courier', 'Nigeria');
insert into coches (id, marca, modelo, pais) values (235, 'Cadillac', 'Seville', 'Colombia');
insert into coches (id, marca, modelo, pais) values (236, 'Infiniti', 'G', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (237, 'Mercedes-Benz', 'E-Class', 'China');
insert into coches (id, marca, modelo, pais) values (238, 'Eagle', 'Vision', 'China');
insert into coches (id, marca, modelo, pais) values (239, 'Kia', 'Forte', 'Croatia');
insert into coches (id, marca, modelo, pais) values (240, 'Dodge', 'D250', 'Portugal');
insert into coches (id, marca, modelo, pais) values (241, 'Toyota', 'Corolla', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (242, 'Ford', 'Edge', 'China');
insert into coches (id, marca, modelo, pais) values (243, 'BMW', '3 Series', 'Canada');
insert into coches (id, marca, modelo, pais) values (244, 'Land Rover', 'Defender', 'Russia');
insert into coches (id, marca, modelo, pais) values (245, 'Dodge', 'Ram Van 2500', 'Argentina');
insert into coches (id, marca, modelo, pais) values (246, 'Jeep', 'Compass', 'Mexico');
insert into coches (id, marca, modelo, pais) values (247, 'BMW', '1 Series', 'Japan');
insert into coches (id, marca, modelo, pais) values (248, 'Honda', 'Odyssey', 'Portugal');
insert into coches (id, marca, modelo, pais) values (249, 'Mercedes-Benz', 'CL-Class', 'Portugal');
insert into coches (id, marca, modelo, pais) values (250, 'Chevrolet', 'HHR', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (251, 'Nissan', '350Z', 'Portugal');
insert into coches (id, marca, modelo, pais) values (252, 'Mercedes-Benz', '300CE', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (253, 'Toyota', 'Sienna', 'Mauritius');
insert into coches (id, marca, modelo, pais) values (254, 'Volkswagen', 'Passat', 'Portugal');
insert into coches (id, marca, modelo, pais) values (255, 'Toyota', '4Runner', 'Yemen');
insert into coches (id, marca, modelo, pais) values (256, 'Infiniti', 'I', 'Costa Rica');
insert into coches (id, marca, modelo, pais) values (257, 'Volvo', 'C30', 'Russia');
insert into coches (id, marca, modelo, pais) values (258, 'Aston Martin', 'DB9', 'Iran');
insert into coches (id, marca, modelo, pais) values (259, 'Bentley', 'Continental', 'Philippines');
insert into coches (id, marca, modelo, pais) values (260, 'Mazda', 'MX-5', 'China');
insert into coches (id, marca, modelo, pais) values (261, 'Mazda', 'B-Series', 'United States');
insert into coches (id, marca, modelo, pais) values (262, 'Isuzu', 'Trooper', 'Sweden');
insert into coches (id, marca, modelo, pais) values (263, 'Ford', 'Escape', 'Ghana');
insert into coches (id, marca, modelo, pais) values (264, 'Pontiac', 'Bonneville', 'Czech Republic');
insert into coches (id, marca, modelo, pais) values (265, 'Mazda', '929', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (266, 'GMC', 'Sierra 1500', 'Bosnia and Herzegovina');
insert into coches (id, marca, modelo, pais) values (267, 'Chrysler', 'Sebring', 'Russia');
insert into coches (id, marca, modelo, pais) values (268, 'Pontiac', 'Vibe', 'United States');
insert into coches (id, marca, modelo, pais) values (269, 'Pontiac', 'Sunbird', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (270, 'Ford', 'Ranger', 'Nigeria');
insert into coches (id, marca, modelo, pais) values (271, 'Mitsubishi', 'Endeavor', 'China');
insert into coches (id, marca, modelo, pais) values (272, 'Dodge', 'Dakota', 'China');
insert into coches (id, marca, modelo, pais) values (273, 'Volkswagen', 'Jetta', 'Sweden');
insert into coches (id, marca, modelo, pais) values (274, 'Volvo', '850', 'China');
insert into coches (id, marca, modelo, pais) values (275, 'GMC', 'Sierra 2500', 'United Arab Emirates');
insert into coches (id, marca, modelo, pais) values (276, 'Volkswagen', 'Passat', 'Russia');
insert into coches (id, marca, modelo, pais) values (277, 'Ford', 'Club Wagon', 'Philippines');
insert into coches (id, marca, modelo, pais) values (278, 'Nissan', 'Murano', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (279, 'Dodge', 'Avenger', 'Taiwan');
insert into coches (id, marca, modelo, pais) values (280, 'Dodge', 'Viper RT/10', 'Croatia');
insert into coches (id, marca, modelo, pais) values (281, 'BMW', '5 Series', 'Sweden');
insert into coches (id, marca, modelo, pais) values (282, 'Chevrolet', '2500', 'Philippines');
insert into coches (id, marca, modelo, pais) values (283, 'Toyota', '4Runner', 'Sweden');
insert into coches (id, marca, modelo, pais) values (284, 'Isuzu', 'Amigo', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (285, 'Chevrolet', 'Express 1500', 'China');
insert into coches (id, marca, modelo, pais) values (286, 'Mercury', 'Sable', 'China');
insert into coches (id, marca, modelo, pais) values (287, 'BMW', '5 Series', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (288, 'Saturn', 'L-Series', 'Nigeria');
insert into coches (id, marca, modelo, pais) values (289, 'Mitsubishi', 'Cordia', 'Greece');
insert into coches (id, marca, modelo, pais) values (290, 'Lexus', 'LX', 'Russia');
insert into coches (id, marca, modelo, pais) values (291, 'Subaru', 'Legacy', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (292, 'Infiniti', 'EX', 'France');
insert into coches (id, marca, modelo, pais) values (293, 'Oldsmobile', 'Achieva', 'Japan');
insert into coches (id, marca, modelo, pais) values (294, 'Dodge', 'Ram Van 2500', 'China');
insert into coches (id, marca, modelo, pais) values (295, 'Mazda', 'Mazdaspeed6', 'Kuwait');
insert into coches (id, marca, modelo, pais) values (296, 'Pontiac', 'Grand Prix', 'Czech Republic');
insert into coches (id, marca, modelo, pais) values (297, 'Chevrolet', 'HHR Panel', 'Japan');
insert into coches (id, marca, modelo, pais) values (298, 'Audi', 'riolet', 'Czech Republic');
insert into coches (id, marca, modelo, pais) values (299, 'Lexus', 'LS', 'Philippines');
insert into coches (id, marca, modelo, pais) values (300, 'Kia', 'Optima', 'Honduras');
insert into coches (id, marca, modelo, pais) values (301, 'Volkswagen', 'GTI', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (302, 'Nissan', 'Altima', 'Cambodia');
insert into coches (id, marca, modelo, pais) values (303, 'Volkswagen', 'Tiguan', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (304, 'Subaru', 'Leone', 'Ireland');
insert into coches (id, marca, modelo, pais) values (305, 'Nissan', 'Frontier', 'China');
insert into coches (id, marca, modelo, pais) values (306, 'Chevrolet', 'Tracker', 'Russia');
insert into coches (id, marca, modelo, pais) values (307, 'Lexus', 'ES', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (308, 'Mazda', 'MX-3', 'Georgia');
insert into coches (id, marca, modelo, pais) values (309, 'Buick', 'LaCrosse', 'Thailand');
insert into coches (id, marca, modelo, pais) values (310, 'Lexus', 'IS', 'Latvia');
insert into coches (id, marca, modelo, pais) values (311, 'Mazda', 'Tribute', 'Russia');
insert into coches (id, marca, modelo, pais) values (312, 'Chrysler', 'Concorde', 'China');
insert into coches (id, marca, modelo, pais) values (313, 'Isuzu', 'Rodeo', 'Peru');
insert into coches (id, marca, modelo, pais) values (314, 'GMC', 'Safari', 'China');
insert into coches (id, marca, modelo, pais) values (315, 'Honda', 'CR-V', 'Ukraine');
insert into coches (id, marca, modelo, pais) values (316, 'Mercury', 'Mystique', 'Poland');
insert into coches (id, marca, modelo, pais) values (317, 'Hyundai', 'Sonata', 'Palau');
insert into coches (id, marca, modelo, pais) values (318, 'Kia', 'Sephia', 'China');
insert into coches (id, marca, modelo, pais) values (319, 'Toyota', 'Solara', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (320, 'Chevrolet', 'Silverado 2500', 'Honduras');
insert into coches (id, marca, modelo, pais) values (321, 'Subaru', 'Legacy', 'Sweden');
insert into coches (id, marca, modelo, pais) values (322, 'Mitsubishi', 'Galant', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (323, 'Ford', 'Bronco II', 'Ukraine');
insert into coches (id, marca, modelo, pais) values (324, 'Chevrolet', 'Suburban 2500', 'Honduras');
insert into coches (id, marca, modelo, pais) values (325, 'Ford', 'Aspire', 'China');
insert into coches (id, marca, modelo, pais) values (326, 'Mitsubishi', 'Outlander', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (327, 'Dodge', 'Ram Van 1500', 'Poland');
insert into coches (id, marca, modelo, pais) values (328, 'BMW', 'M5', 'Russia');
insert into coches (id, marca, modelo, pais) values (329, 'Honda', 'CR-V', 'Bulgaria');
insert into coches (id, marca, modelo, pais) values (330, 'Isuzu', 'Hombre Space', 'Poland');
insert into coches (id, marca, modelo, pais) values (331, 'Volkswagen', 'Eurovan', 'Russia');
insert into coches (id, marca, modelo, pais) values (332, 'Mazda', 'Familia', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (333, 'Toyota', 'Tacoma', 'Czech Republic');
insert into coches (id, marca, modelo, pais) values (334, 'Suzuki', 'SJ', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (335, 'GMC', 'Yukon', 'Philippines');
insert into coches (id, marca, modelo, pais) values (336, 'Toyota', 'Camry Solara', 'Portugal');
insert into coches (id, marca, modelo, pais) values (337, 'Chrysler', 'Town & Country', 'Portugal');
insert into coches (id, marca, modelo, pais) values (338, 'Lexus', 'SC', 'Portugal');
insert into coches (id, marca, modelo, pais) values (339, 'Toyota', 'Avalon', 'Brazil');
insert into coches (id, marca, modelo, pais) values (340, 'Toyota', 'Previa', 'China');
insert into coches (id, marca, modelo, pais) values (341, 'Toyota', 'Tacoma', 'Slovenia');
insert into coches (id, marca, modelo, pais) values (342, 'Kia', 'Sedona', 'Canada');
insert into coches (id, marca, modelo, pais) values (343, 'Chevrolet', 'Avalanche', 'Portugal');
insert into coches (id, marca, modelo, pais) values (344, 'Subaru', 'Legacy', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (345, 'Volvo', 'S80', 'Mayotte');
insert into coches (id, marca, modelo, pais) values (346, 'Lincoln', 'Continental', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (347, 'Mazda', 'RX-7', 'Iceland');
insert into coches (id, marca, modelo, pais) values (348, 'Chevrolet', 'Tracker', 'Peru');
insert into coches (id, marca, modelo, pais) values (349, 'Honda', 'CR-Z', 'Israel');
insert into coches (id, marca, modelo, pais) values (350, 'BMW', '330', 'Norway');
insert into coches (id, marca, modelo, pais) values (351, 'Buick', 'Coachbuilder', 'Finland');
insert into coches (id, marca, modelo, pais) values (352, 'GMC', 'Savana 3500', 'Afghanistan');
insert into coches (id, marca, modelo, pais) values (353, 'Saab', '9-7X', 'China');
insert into coches (id, marca, modelo, pais) values (354, 'Toyota', 'Corolla', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (355, 'Chevrolet', 'Tahoe', 'Philippines');
insert into coches (id, marca, modelo, pais) values (356, 'Nissan', 'Quest', 'China');
insert into coches (id, marca, modelo, pais) values (357, 'Suzuki', 'Verona', 'Morocco');
insert into coches (id, marca, modelo, pais) values (358, 'Ford', 'Club Wagon', 'Philippines');
insert into coches (id, marca, modelo, pais) values (359, 'Volkswagen', 'Cabriolet', 'Czech Republic');
insert into coches (id, marca, modelo, pais) values (360, 'Toyota', 'Land Cruiser', 'China');
insert into coches (id, marca, modelo, pais) values (361, 'Subaru', 'Impreza', 'Morocco');
insert into coches (id, marca, modelo, pais) values (362, 'Mercedes-Benz', 'SLS-Class', 'Guatemala');
insert into coches (id, marca, modelo, pais) values (363, 'Mazda', 'Mazdaspeed6', 'China');
insert into coches (id, marca, modelo, pais) values (364, 'Infiniti', 'I', 'Venezuela');
insert into coches (id, marca, modelo, pais) values (365, 'Ford', 'E-Series', 'Japan');
insert into coches (id, marca, modelo, pais) values (366, 'Mercedes-Benz', 'M-Class', 'Jamaica');
insert into coches (id, marca, modelo, pais) values (367, 'Saturn', 'S-Series', 'Portugal');
insert into coches (id, marca, modelo, pais) values (368, 'Pontiac', 'Bonneville', 'China');
insert into coches (id, marca, modelo, pais) values (369, 'Suzuki', 'Grand Vitara', 'Brazil');
insert into coches (id, marca, modelo, pais) values (370, 'GMC', 'Savana 2500', 'United States');
insert into coches (id, marca, modelo, pais) values (371, 'Ford', 'Crown Victoria', 'Serbia');
insert into coches (id, marca, modelo, pais) values (372, 'GMC', 'Rally Wagon 1500', 'South Africa');
insert into coches (id, marca, modelo, pais) values (373, 'BMW', '525', 'Ukraine');
insert into coches (id, marca, modelo, pais) values (374, 'Volkswagen', 'Cabriolet', 'Greece');
insert into coches (id, marca, modelo, pais) values (375, 'Land Rover', 'Range Rover Sport', 'Argentina');
insert into coches (id, marca, modelo, pais) values (376, 'Oldsmobile', 'Bravada', 'Taiwan');
insert into coches (id, marca, modelo, pais) values (377, 'Honda', 'Civic', 'Syria');
insert into coches (id, marca, modelo, pais) values (378, 'Lincoln', 'Town Car', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (379, 'Jeep', 'Commander', 'Laos');
insert into coches (id, marca, modelo, pais) values (380, 'Ford', 'F-Series', 'Czech Republic');
insert into coches (id, marca, modelo, pais) values (381, 'Porsche', '968', 'Belarus');
insert into coches (id, marca, modelo, pais) values (382, 'Chrysler', 'Cirrus', 'Nigeria');
insert into coches (id, marca, modelo, pais) values (383, 'Volvo', 'S40', 'China');
insert into coches (id, marca, modelo, pais) values (384, 'Mitsubishi', 'Eclipse', 'Philippines');
insert into coches (id, marca, modelo, pais) values (385, 'Hyundai', 'Tiburon', 'Slovenia');
insert into coches (id, marca, modelo, pais) values (386, 'Ford', 'Explorer', 'Japan');
insert into coches (id, marca, modelo, pais) values (387, 'Chevrolet', 'Impala', 'Philippines');
insert into coches (id, marca, modelo, pais) values (388, 'BMW', '5 Series', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (389, 'Acura', 'NSX', 'Norway');
insert into coches (id, marca, modelo, pais) values (390, 'Pontiac', 'GTO', 'China');
insert into coches (id, marca, modelo, pais) values (391, 'Audi', 'RS4', 'Brazil');
insert into coches (id, marca, modelo, pais) values (392, 'Lincoln', 'Mark VIII', 'Russia');
insert into coches (id, marca, modelo, pais) values (393, 'Chevrolet', 'Tahoe', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (394, 'Audi', 'A8', 'Canada');
insert into coches (id, marca, modelo, pais) values (395, 'GMC', 'Envoy', 'Russia');
insert into coches (id, marca, modelo, pais) values (396, 'Ford', 'Focus', 'Ukraine');
insert into coches (id, marca, modelo, pais) values (397, 'Oldsmobile', 'Silhouette', 'China');
insert into coches (id, marca, modelo, pais) values (398, 'Infiniti', 'FX', 'Albania');
insert into coches (id, marca, modelo, pais) values (399, 'Suzuki', 'Grand Vitara', 'Italy');
insert into coches (id, marca, modelo, pais) values (400, 'Chrysler', 'Voyager', 'France');
insert into coches (id, marca, modelo, pais) values (401, 'Subaru', 'Forester', 'Philippines');
insert into coches (id, marca, modelo, pais) values (402, 'Dodge', 'Ram 1500', 'Brazil');
insert into coches (id, marca, modelo, pais) values (403, 'Ford', 'Courier', 'China');
insert into coches (id, marca, modelo, pais) values (404, 'Toyota', 'Previa', 'Greece');
insert into coches (id, marca, modelo, pais) values (405, 'Cadillac', 'Escalade EXT', 'Brazil');
insert into coches (id, marca, modelo, pais) values (406, 'Chevrolet', 'Impala', 'China');
insert into coches (id, marca, modelo, pais) values (407, 'Mazda', 'Familia', 'Ireland');
insert into coches (id, marca, modelo, pais) values (408, 'Cadillac', 'Escalade ESV', 'Argentina');
insert into coches (id, marca, modelo, pais) values (409, 'Porsche', 'Carrera GT', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (410, 'Chevrolet', 'Suburban', 'Brazil');
insert into coches (id, marca, modelo, pais) values (411, 'Honda', 'CR-V', 'Norway');
insert into coches (id, marca, modelo, pais) values (412, 'Lexus', 'SC', 'Brazil');
insert into coches (id, marca, modelo, pais) values (413, 'Isuzu', 'Amigo', 'Tanzania');
insert into coches (id, marca, modelo, pais) values (414, 'Toyota', 'Sienna', 'China');
insert into coches (id, marca, modelo, pais) values (415, 'GMC', 'Savana 2500', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (416, 'Nissan', '350Z', 'Poland');
insert into coches (id, marca, modelo, pais) values (417, 'Audi', '80', 'Greece');
insert into coches (id, marca, modelo, pais) values (418, 'Spyker', 'C8 Spyder Wide Body', 'Portugal');
insert into coches (id, marca, modelo, pais) values (419, 'Ford', 'Focus', 'France');
insert into coches (id, marca, modelo, pais) values (420, 'Dodge', 'Sprinter', 'Albania');
insert into coches (id, marca, modelo, pais) values (421, 'GMC', 'Vandura G2500', 'Philippines');
insert into coches (id, marca, modelo, pais) values (422, 'MINI', 'Cooper Clubman', 'El Salvador');
insert into coches (id, marca, modelo, pais) values (423, 'Toyota', 'Land Cruiser', 'Philippines');
insert into coches (id, marca, modelo, pais) values (424, 'Oldsmobile', '98', 'China');
insert into coches (id, marca, modelo, pais) values (425, 'Lotus', 'Exige', 'Philippines');
insert into coches (id, marca, modelo, pais) values (426, 'Nissan', 'Murano', 'China');
insert into coches (id, marca, modelo, pais) values (427, 'Lincoln', 'LS', 'Ukraine');
insert into coches (id, marca, modelo, pais) values (428, 'Plymouth', 'Grand Voyager', 'Honduras');
insert into coches (id, marca, modelo, pais) values (429, 'BMW', 'M', 'Portugal');
insert into coches (id, marca, modelo, pais) values (430, 'Chevrolet', 'S10', 'Uganda');
insert into coches (id, marca, modelo, pais) values (431, 'Buick', 'Rainier', 'Portugal');
insert into coches (id, marca, modelo, pais) values (432, 'GMC', 'Acadia', 'China');
insert into coches (id, marca, modelo, pais) values (433, 'Hyundai', 'Sonata', 'Philippines');
insert into coches (id, marca, modelo, pais) values (434, 'Chrysler', 'Town & Country', 'Russia');
insert into coches (id, marca, modelo, pais) values (435, 'Mitsubishi', 'Eclipse', 'Egypt');
insert into coches (id, marca, modelo, pais) values (436, 'Volkswagen', 'Tiguan', 'Japan');
insert into coches (id, marca, modelo, pais) values (437, 'Ford', 'F250', 'Egypt');
insert into coches (id, marca, modelo, pais) values (438, 'Oldsmobile', 'Cutlass Supreme', 'Brazil');
insert into coches (id, marca, modelo, pais) values (439, 'Chevrolet', 'Lumina', 'Azerbaijan');
insert into coches (id, marca, modelo, pais) values (440, 'Pontiac', 'Gemini', 'Brazil');
insert into coches (id, marca, modelo, pais) values (441, 'Chrysler', 'Town & Country', 'Philippines');
insert into coches (id, marca, modelo, pais) values (442, 'Hyundai', 'Equus', 'France');
insert into coches (id, marca, modelo, pais) values (443, 'Buick', 'Century', 'Ukraine');
insert into coches (id, marca, modelo, pais) values (444, 'Honda', 'Odyssey', 'Portugal');
insert into coches (id, marca, modelo, pais) values (445, 'Volkswagen', 'Eurovan', 'Czech Republic');
insert into coches (id, marca, modelo, pais) values (446, 'Dodge', 'Ram Van 1500', 'Philippines');
insert into coches (id, marca, modelo, pais) values (447, 'Mercedes-Benz', 'G-Class', 'Russia');
insert into coches (id, marca, modelo, pais) values (448, 'Chrysler', 'Prowler', 'China');
insert into coches (id, marca, modelo, pais) values (449, 'Chevrolet', 'Suburban 2500', 'Peru');
insert into coches (id, marca, modelo, pais) values (450, 'Geo', 'Metro', 'Pakistan');
insert into coches (id, marca, modelo, pais) values (451, 'Mazda', 'RX-7', 'Russia');
insert into coches (id, marca, modelo, pais) values (452, 'Dodge', 'Magnum', 'Czech Republic');
insert into coches (id, marca, modelo, pais) values (453, 'Ford', 'Taurus', 'Portugal');
insert into coches (id, marca, modelo, pais) values (454, 'Nissan', 'Maxima', 'Poland');
insert into coches (id, marca, modelo, pais) values (455, 'Lamborghini', 'Diablo', 'Philippines');
insert into coches (id, marca, modelo, pais) values (456, 'Hyundai', 'Accent', 'Brazil');
insert into coches (id, marca, modelo, pais) values (457, 'Chevrolet', 'S10', 'Portugal');
insert into coches (id, marca, modelo, pais) values (458, 'Toyota', 'Land Cruiser', 'France');
insert into coches (id, marca, modelo, pais) values (459, 'Nissan', 'Maxima', 'China');
insert into coches (id, marca, modelo, pais) values (460, 'Toyota', 'Yaris', 'Norway');
insert into coches (id, marca, modelo, pais) values (461, 'Dodge', 'Grand Caravan', 'France');
insert into coches (id, marca, modelo, pais) values (462, 'Volkswagen', 'GTI', 'Russia');
insert into coches (id, marca, modelo, pais) values (463, 'Mazda', 'B-Series', 'China');
insert into coches (id, marca, modelo, pais) values (464, 'Ford', 'Tempo', 'Armenia');
insert into coches (id, marca, modelo, pais) values (465, 'Volkswagen', 'Passat', 'Russia');
insert into coches (id, marca, modelo, pais) values (466, 'Dodge', 'D150', 'Brazil');
insert into coches (id, marca, modelo, pais) values (467, 'Honda', 'Civic', 'Colombia');
insert into coches (id, marca, modelo, pais) values (468, 'GMC', 'Savana 2500', 'China');
insert into coches (id, marca, modelo, pais) values (469, 'Chrysler', '300', 'Greece');
insert into coches (id, marca, modelo, pais) values (470, 'Mazda', 'Mazdaspeed6', 'China');
insert into coches (id, marca, modelo, pais) values (471, 'Oldsmobile', 'Alero', 'Colombia');
insert into coches (id, marca, modelo, pais) values (472, 'Subaru', 'Alcyone SVX', 'China');
insert into coches (id, marca, modelo, pais) values (473, 'Ford', 'F150', 'Nicaragua');
insert into coches (id, marca, modelo, pais) values (474, 'Toyota', 'Celica', 'China');
insert into coches (id, marca, modelo, pais) values (475, 'Aston Martin', 'V8 Vantage', 'Syria');
insert into coches (id, marca, modelo, pais) values (476, 'Hummer', 'H2', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (477, 'GMC', 'Yukon Denali', 'Russia');
insert into coches (id, marca, modelo, pais) values (478, 'Suzuki', 'Esteem', 'France');
insert into coches (id, marca, modelo, pais) values (479, 'Cadillac', 'Escalade EXT', 'Philippines');
insert into coches (id, marca, modelo, pais) values (480, 'Toyota', 'Highlander', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (481, 'Mercury', 'Tracer', 'Honduras');
insert into coches (id, marca, modelo, pais) values (482, 'Suzuki', 'Cultus', 'Poland');
insert into coches (id, marca, modelo, pais) values (483, 'Dodge', 'Charger', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (484, 'Pontiac', 'Firefly', 'Russia');
insert into coches (id, marca, modelo, pais) values (485, 'Toyota', 'FJ Cruiser', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (486, 'Mazda', 'Familia', 'Russia');
insert into coches (id, marca, modelo, pais) values (487, 'Hyundai', 'Elantra', 'Japan');
insert into coches (id, marca, modelo, pais) values (488, 'Buick', 'LeSabre', 'Philippines');
insert into coches (id, marca, modelo, pais) values (489, 'Mazda', 'RX-7', 'Russia');
insert into coches (id, marca, modelo, pais) values (490, 'Dodge', 'Dakota Club', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (491, 'Mercury', 'Milan', 'Philippines');
insert into coches (id, marca, modelo, pais) values (492, 'Jeep', 'Wrangler', 'Portugal');
insert into coches (id, marca, modelo, pais) values (493, 'Eagle', 'Vision', 'Philippines');
insert into coches (id, marca, modelo, pais) values (494, 'Mercury', 'Tracer', 'Cuba');
insert into coches (id, marca, modelo, pais) values (495, 'GMC', '3500 Club Coupe', 'Greece');
insert into coches (id, marca, modelo, pais) values (496, 'Lincoln', 'Mark VII', 'Sweden');
insert into coches (id, marca, modelo, pais) values (497, 'Bentley', 'Brooklands', 'Panama');
insert into coches (id, marca, modelo, pais) values (498, 'Ford', 'Ranger', 'Czech Republic');
insert into coches (id, marca, modelo, pais) values (499, 'Mercedes-Benz', 'SL-Class', 'Venezuela');
insert into coches (id, marca, modelo, pais) values (500, 'Mercury', 'Milan', 'Hungary');
insert into coches (id, marca, modelo, pais) values (501, 'Saab', '9-3', 'Bosnia and Herzegovina');
insert into coches (id, marca, modelo, pais) values (502, 'Land Rover', 'Discovery', 'Argentina');
insert into coches (id, marca, modelo, pais) values (503, 'Infiniti', 'G35', 'Myanmar');
insert into coches (id, marca, modelo, pais) values (504, 'Lexus', 'SC', 'Thailand');
insert into coches (id, marca, modelo, pais) values (505, 'GMC', '3500 Club Coupe', 'Ukraine');
insert into coches (id, marca, modelo, pais) values (506, 'Toyota', 'Highlander', 'Cambodia');
insert into coches (id, marca, modelo, pais) values (507, 'Ford', 'F350', 'France');
insert into coches (id, marca, modelo, pais) values (508, 'Ford', 'Mustang', 'Russia');
insert into coches (id, marca, modelo, pais) values (509, 'Audi', 'A5', 'Peru');
insert into coches (id, marca, modelo, pais) values (510, 'Honda', 'Odyssey', 'China');
insert into coches (id, marca, modelo, pais) values (511, 'Pontiac', 'Grand Am', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (512, 'GMC', '2500', 'Philippines');
insert into coches (id, marca, modelo, pais) values (513, 'Chevrolet', 'Blazer', 'China');
insert into coches (id, marca, modelo, pais) values (514, 'Audi', 'A3', 'Ukraine');
insert into coches (id, marca, modelo, pais) values (515, 'BMW', 'X3', 'Japan');
insert into coches (id, marca, modelo, pais) values (516, 'Ford', 'F250', 'Poland');
insert into coches (id, marca, modelo, pais) values (517, 'Buick', 'LeSabre', 'China');
insert into coches (id, marca, modelo, pais) values (518, 'Mitsubishi', 'Mirage', 'Philippines');
insert into coches (id, marca, modelo, pais) values (519, 'Acura', 'NSX', 'Greece');
insert into coches (id, marca, modelo, pais) values (520, 'Mitsubishi', 'Endeavor', 'Brazil');
insert into coches (id, marca, modelo, pais) values (521, 'Ford', 'Thunderbird', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (522, 'Toyota', 'Avalon', 'Croatia');
insert into coches (id, marca, modelo, pais) values (523, 'Jeep', 'Grand Cherokee', 'Cuba');
insert into coches (id, marca, modelo, pais) values (524, 'Dodge', 'Caliber', 'France');
insert into coches (id, marca, modelo, pais) values (525, 'Pontiac', 'Firebird', 'Philippines');
insert into coches (id, marca, modelo, pais) values (526, 'Mercedes-Benz', 'SL-Class', 'South Africa');
insert into coches (id, marca, modelo, pais) values (527, 'Volvo', 'XC90', 'Vietnam');
insert into coches (id, marca, modelo, pais) values (528, 'Buick', 'LaCrosse', 'China');
insert into coches (id, marca, modelo, pais) values (529, 'Honda', 'S2000', 'China');
insert into coches (id, marca, modelo, pais) values (530, 'Ford', 'Crown Victoria', 'Colombia');
insert into coches (id, marca, modelo, pais) values (531, 'Lincoln', 'MKS', 'Morocco');
insert into coches (id, marca, modelo, pais) values (532, 'Plymouth', 'Acclaim', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (533, 'Volvo', 'XC60', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (534, 'Hyundai', 'HED-5', 'Russia');
insert into coches (id, marca, modelo, pais) values (535, 'Mazda', '626', 'Latvia');
insert into coches (id, marca, modelo, pais) values (536, 'Lincoln', 'Continental Mark VII', 'China');
insert into coches (id, marca, modelo, pais) values (537, 'Chrysler', 'PT Cruiser', 'China');
insert into coches (id, marca, modelo, pais) values (538, 'Volkswagen', 'Scirocco', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (539, 'Volkswagen', 'Passat', 'Uruguay');
insert into coches (id, marca, modelo, pais) values (540, 'Suzuki', 'Reno', 'Armenia');
insert into coches (id, marca, modelo, pais) values (541, 'Lincoln', 'Town Car', 'Japan');
insert into coches (id, marca, modelo, pais) values (542, 'Honda', 'Ridgeline', 'China');
insert into coches (id, marca, modelo, pais) values (543, 'Toyota', 'Tacoma Xtra', 'China');
insert into coches (id, marca, modelo, pais) values (544, 'Hyundai', 'Sonata', 'Philippines');
insert into coches (id, marca, modelo, pais) values (545, 'Chevrolet', 'Tahoe', 'Mexico');
insert into coches (id, marca, modelo, pais) values (546, 'Plymouth', 'Breeze', 'Czech Republic');
insert into coches (id, marca, modelo, pais) values (547, 'Mitsubishi', 'Chariot', 'Russia');
insert into coches (id, marca, modelo, pais) values (548, 'Toyota', 'Tercel', 'Nigeria');
insert into coches (id, marca, modelo, pais) values (549, 'Jaguar', 'XJ Series', 'Philippines');
insert into coches (id, marca, modelo, pais) values (550, 'Lamborghini', 'Diablo', 'Albania');
insert into coches (id, marca, modelo, pais) values (551, 'Honda', 'CR-Z', 'United States');
insert into coches (id, marca, modelo, pais) values (552, 'Cadillac', 'XLR-V', 'Brazil');
insert into coches (id, marca, modelo, pais) values (553, 'Pontiac', 'Grand Am', 'Canada');
insert into coches (id, marca, modelo, pais) values (554, 'Land Rover', 'Discovery', 'Libya');
insert into coches (id, marca, modelo, pais) values (555, 'Mazda', 'MX-5', 'Colombia');
insert into coches (id, marca, modelo, pais) values (556, 'Kia', 'Sorento', 'Argentina');
insert into coches (id, marca, modelo, pais) values (557, 'Audi', 'Coupe GT', 'Portugal');
insert into coches (id, marca, modelo, pais) values (558, 'Subaru', 'Legacy', 'Portugal');
insert into coches (id, marca, modelo, pais) values (559, 'Suzuki', 'Vitara', 'Russia');
insert into coches (id, marca, modelo, pais) values (560, 'Infiniti', 'G37', 'China');
insert into coches (id, marca, modelo, pais) values (561, 'Honda', 'Accord Crosstour', 'China');
insert into coches (id, marca, modelo, pais) values (562, 'Ram', '1500', 'Fiji');
insert into coches (id, marca, modelo, pais) values (563, 'Mazda', 'Mazda3', 'China');
insert into coches (id, marca, modelo, pais) values (564, 'Mitsubishi', 'Endeavor', 'Russia');
insert into coches (id, marca, modelo, pais) values (565, 'Dodge', 'Ram Wagon B150', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (566, 'Dodge', 'Ram Van 3500', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (567, 'Cadillac', 'STS-V', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (568, 'Audi', 'A4', 'Thailand');
insert into coches (id, marca, modelo, pais) values (569, 'Ford', 'F250', 'Macedonia');
insert into coches (id, marca, modelo, pais) values (570, 'Chevrolet', 'Corsica', 'Ireland');
insert into coches (id, marca, modelo, pais) values (571, 'Mercury', 'Milan', 'Czech Republic');
insert into coches (id, marca, modelo, pais) values (572, 'Pontiac', 'Vibe', 'Malaysia');
insert into coches (id, marca, modelo, pais) values (573, 'Chevrolet', 'Metro', 'Poland');
insert into coches (id, marca, modelo, pais) values (574, 'BMW', '3 Series', 'Finland');
insert into coches (id, marca, modelo, pais) values (575, 'Chevrolet', 'S10 Blazer', 'China');
insert into coches (id, marca, modelo, pais) values (576, 'Dodge', 'Caravan', 'Jordan');
insert into coches (id, marca, modelo, pais) values (577, 'GMC', 'Sierra 2500', 'Poland');
insert into coches (id, marca, modelo, pais) values (578, 'Chevrolet', 'Blazer', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (579, 'Hyundai', 'Accent', 'China');
insert into coches (id, marca, modelo, pais) values (580, 'Buick', 'Regal', 'Philippines');
insert into coches (id, marca, modelo, pais) values (581, 'Chevrolet', 'G-Series G20', 'Russia');
insert into coches (id, marca, modelo, pais) values (582, 'GMC', '3500 Club Coupe', 'China');
insert into coches (id, marca, modelo, pais) values (583, 'Acura', 'ZDX', 'Serbia');
insert into coches (id, marca, modelo, pais) values (584, 'Ford', 'Mustang', 'China');
insert into coches (id, marca, modelo, pais) values (585, 'Toyota', 'Tacoma', 'France');
insert into coches (id, marca, modelo, pais) values (586, 'Lexus', 'LS Hybrid', 'United States');
insert into coches (id, marca, modelo, pais) values (587, 'Acura', 'MDX', 'Venezuela');
insert into coches (id, marca, modelo, pais) values (588, 'Mercedes-Benz', 'S-Class', 'Brazil');
insert into coches (id, marca, modelo, pais) values (589, 'Pontiac', 'Grand Prix', 'United Kingdom');
insert into coches (id, marca, modelo, pais) values (590, 'Volkswagen', 'Golf', 'Greece');
insert into coches (id, marca, modelo, pais) values (591, 'Pontiac', 'Sunbird', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (592, 'Buick', 'Century', 'Morocco');
insert into coches (id, marca, modelo, pais) values (593, 'Mercury', 'Mystique', 'Croatia');
insert into coches (id, marca, modelo, pais) values (594, 'Chrysler', 'Pacifica', 'Vietnam');
insert into coches (id, marca, modelo, pais) values (595, 'Pontiac', 'GTO', 'China');
insert into coches (id, marca, modelo, pais) values (596, 'Bentley', 'Continental', 'Thailand');
insert into coches (id, marca, modelo, pais) values (597, 'Honda', 'CR-Z', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (598, 'Volvo', 'V40', 'China');
insert into coches (id, marca, modelo, pais) values (599, 'Lexus', 'ES', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (600, 'Lotus', 'Esprit', 'France');
insert into coches (id, marca, modelo, pais) values (601, 'Acura', 'Legend', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (602, 'Nissan', 'Sentra', 'Argentina');
insert into coches (id, marca, modelo, pais) values (603, 'Infiniti', 'QX56', 'Lithuania');
insert into coches (id, marca, modelo, pais) values (604, 'Mitsubishi', 'GTO', 'Norway');
insert into coches (id, marca, modelo, pais) values (605, 'Lexus', 'LX', 'China');
insert into coches (id, marca, modelo, pais) values (606, 'Chrysler', 'Imperial', 'Mexico');
insert into coches (id, marca, modelo, pais) values (607, 'Honda', 'Passport', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (608, 'Oldsmobile', 'Silhouette', 'China');
insert into coches (id, marca, modelo, pais) values (609, 'Cadillac', 'Seville', 'Kyrgyzstan');
insert into coches (id, marca, modelo, pais) values (610, 'Mazda', 'B-Series', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (611, 'Pontiac', 'Gemini', 'Afghanistan');
insert into coches (id, marca, modelo, pais) values (612, 'Chevrolet', 'Aveo', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (613, 'Porsche', 'Cayman', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (614, 'Chevrolet', 'Camaro', 'Brazil');
insert into coches (id, marca, modelo, pais) values (615, 'Subaru', 'Forester', 'Portugal');
insert into coches (id, marca, modelo, pais) values (616, 'Toyota', 'Tundra', 'China');
insert into coches (id, marca, modelo, pais) values (617, 'Dodge', 'Daytona', 'Czech Republic');
insert into coches (id, marca, modelo, pais) values (618, 'Lamborghini', 'Gallardo', 'China');
insert into coches (id, marca, modelo, pais) values (619, 'Austin', 'Mini Cooper', 'Thailand');
insert into coches (id, marca, modelo, pais) values (620, 'Subaru', 'Impreza', 'Libya');
insert into coches (id, marca, modelo, pais) values (621, 'Chevrolet', 'Suburban 2500', 'Ecuador');
insert into coches (id, marca, modelo, pais) values (622, 'Pontiac', 'Firefly', 'Mauritania');
insert into coches (id, marca, modelo, pais) values (623, 'Jeep', 'Wrangler', 'Brazil');
insert into coches (id, marca, modelo, pais) values (624, 'Chrysler', 'Concorde', 'Brazil');
insert into coches (id, marca, modelo, pais) values (625, 'Land Rover', 'Range Rover Sport', 'Japan');
insert into coches (id, marca, modelo, pais) values (626, 'BMW', '5 Series', 'Russia');
insert into coches (id, marca, modelo, pais) values (627, 'Ford', 'Focus', 'Croatia');
insert into coches (id, marca, modelo, pais) values (628, 'Lincoln', 'Continental', 'United States');
insert into coches (id, marca, modelo, pais) values (629, 'Aston Martin', 'Virage', 'Germany');
insert into coches (id, marca, modelo, pais) values (630, 'Ford', 'E-Series', 'Azerbaijan');
insert into coches (id, marca, modelo, pais) values (631, 'Subaru', 'Impreza', 'Brazil');
insert into coches (id, marca, modelo, pais) values (632, 'Mitsubishi', 'Truck', 'China');
insert into coches (id, marca, modelo, pais) values (633, 'Ford', 'Lightning', 'Poland');
insert into coches (id, marca, modelo, pais) values (634, 'Buick', 'Regal', 'China');
insert into coches (id, marca, modelo, pais) values (635, 'Ford', 'Mustang', 'China');
insert into coches (id, marca, modelo, pais) values (636, 'Chevrolet', 'Silverado', 'Thailand');
insert into coches (id, marca, modelo, pais) values (637, 'Jeep', 'Liberty', 'Cuba');
insert into coches (id, marca, modelo, pais) values (638, 'Hummer', 'H2', 'Macedonia');
insert into coches (id, marca, modelo, pais) values (639, 'Chevrolet', 'Silverado 1500', 'Thailand');
insert into coches (id, marca, modelo, pais) values (640, 'Dodge', 'Ram Van 1500', 'China');
insert into coches (id, marca, modelo, pais) values (641, 'Pontiac', 'Aztek', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (642, 'GMC', 'Sonoma Club Coupe', 'China');
insert into coches (id, marca, modelo, pais) values (643, 'Volkswagen', 'Jetta', 'Argentina');
insert into coches (id, marca, modelo, pais) values (644, 'Dodge', 'Ram 2500', 'Philippines');
insert into coches (id, marca, modelo, pais) values (645, 'Porsche', '968', 'Honduras');
insert into coches (id, marca, modelo, pais) values (646, 'Maybach', 'Landaulet', 'Bosnia and Herzegovina');
insert into coches (id, marca, modelo, pais) values (647, 'Mitsubishi', 'Excel', 'Czech Republic');
insert into coches (id, marca, modelo, pais) values (648, 'Volvo', 'C70', 'Malaysia');
insert into coches (id, marca, modelo, pais) values (649, 'Cadillac', 'Seville', 'China');
insert into coches (id, marca, modelo, pais) values (650, 'Audi', 'RS4', 'Canada');
insert into coches (id, marca, modelo, pais) values (651, 'Suzuki', 'Swift', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (652, 'Suzuki', 'SJ 410', 'Portugal');
insert into coches (id, marca, modelo, pais) values (653, 'Chevrolet', 'Impala', 'Russia');
insert into coches (id, marca, modelo, pais) values (654, 'Ford', 'F250', 'Thailand');
insert into coches (id, marca, modelo, pais) values (655, 'Mercury', 'Villager', 'Peru');
insert into coches (id, marca, modelo, pais) values (656, 'Buick', 'Electra', 'Guatemala');
insert into coches (id, marca, modelo, pais) values (657, 'Chrysler', 'New Yorker', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (658, 'Volkswagen', 'R32', 'Pakistan');
insert into coches (id, marca, modelo, pais) values (659, 'Nissan', 'Xterra', 'Peru');
insert into coches (id, marca, modelo, pais) values (660, 'Nissan', 'Pathfinder', 'China');
insert into coches (id, marca, modelo, pais) values (661, 'Mercedes-Benz', 'CLK-Class', 'Philippines');
insert into coches (id, marca, modelo, pais) values (662, 'Infiniti', 'I', 'Ukraine');
insert into coches (id, marca, modelo, pais) values (663, 'BMW', '550', 'Russia');
insert into coches (id, marca, modelo, pais) values (664, 'Chevrolet', 'Tracker', 'Kyrgyzstan');
insert into coches (id, marca, modelo, pais) values (665, 'Jeep', 'Liberty', 'Portugal');
insert into coches (id, marca, modelo, pais) values (666, 'Mitsubishi', 'Outlander', 'Haiti');
insert into coches (id, marca, modelo, pais) values (667, 'Hyundai', 'Santa Fe', 'Marshall Islands');
insert into coches (id, marca, modelo, pais) values (668, 'Hyundai', 'Sonata', 'Thailand');
insert into coches (id, marca, modelo, pais) values (669, 'Ford', 'Tempo', 'Mexico');
insert into coches (id, marca, modelo, pais) values (670, 'Plymouth', 'Neon', 'Portugal');
insert into coches (id, marca, modelo, pais) values (671, 'Mitsubishi', 'Montero', 'Moldova');
insert into coches (id, marca, modelo, pais) values (672, 'Honda', 'Element', 'China');
insert into coches (id, marca, modelo, pais) values (673, 'Mercedes-Benz', 'S-Class', 'China');
insert into coches (id, marca, modelo, pais) values (674, 'Kia', 'Optima', 'Philippines');
insert into coches (id, marca, modelo, pais) values (675, 'GMC', 'Sonoma', 'Egypt');
insert into coches (id, marca, modelo, pais) values (676, 'Chevrolet', 'Cavalier', 'Honduras');
insert into coches (id, marca, modelo, pais) values (677, 'Ford', 'Focus', 'China');
insert into coches (id, marca, modelo, pais) values (678, 'Mercury', 'Grand Marquis', 'United States');
insert into coches (id, marca, modelo, pais) values (679, 'BMW', '745', 'Nigeria');
insert into coches (id, marca, modelo, pais) values (680, 'Mazda', 'B-Series Plus', 'Poland');
insert into coches (id, marca, modelo, pais) values (681, 'Lexus', 'SC', 'Myanmar');
insert into coches (id, marca, modelo, pais) values (682, 'Mercedes-Benz', 'M-Class', 'Russia');
insert into coches (id, marca, modelo, pais) values (683, 'Suzuki', 'Swift', 'Costa Rica');
insert into coches (id, marca, modelo, pais) values (684, 'Toyota', 'RAV4', 'France');
insert into coches (id, marca, modelo, pais) values (685, 'Ford', 'Fiesta', 'Colombia');
insert into coches (id, marca, modelo, pais) values (686, 'Mitsubishi', 'Truck', 'United States');
insert into coches (id, marca, modelo, pais) values (687, 'Suzuki', 'Verona', 'China');
insert into coches (id, marca, modelo, pais) values (688, 'Lexus', 'GS', 'Venezuela');
insert into coches (id, marca, modelo, pais) values (689, 'Chevrolet', 'HHR', 'Argentina');
insert into coches (id, marca, modelo, pais) values (690, 'Hyundai', 'Elantra', 'Nigeria');
insert into coches (id, marca, modelo, pais) values (691, 'BMW', '530', 'Peru');
insert into coches (id, marca, modelo, pais) values (692, 'Dodge', 'Dakota Club', 'Czech Republic');
insert into coches (id, marca, modelo, pais) values (693, 'BMW', 'Z4', 'China');
insert into coches (id, marca, modelo, pais) values (694, 'Saab', '9000', 'Yemen');
insert into coches (id, marca, modelo, pais) values (695, 'Toyota', 'Prius Plug-in Hybrid', 'China');
insert into coches (id, marca, modelo, pais) values (696, 'Subaru', 'Legacy', 'China');
insert into coches (id, marca, modelo, pais) values (697, 'Ford', 'Escape', 'Yemen');
insert into coches (id, marca, modelo, pais) values (698, 'Chevrolet', 'Venture', 'China');
insert into coches (id, marca, modelo, pais) values (699, 'Chevrolet', 'Corvette', 'China');
insert into coches (id, marca, modelo, pais) values (700, 'Ford', 'Explorer', 'Philippines');
insert into coches (id, marca, modelo, pais) values (701, 'Ford', 'Fusion', 'Brazil');
insert into coches (id, marca, modelo, pais) values (702, 'Toyota', 'Land Cruiser', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (703, 'Lexus', 'LS', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (704, 'Mazda', 'Miata MX-5', 'Bulgaria');
insert into coches (id, marca, modelo, pais) values (705, 'Mitsubishi', 'Mirage', 'Philippines');
insert into coches (id, marca, modelo, pais) values (706, 'Chevrolet', 'Camaro', 'Iran');
insert into coches (id, marca, modelo, pais) values (707, 'Lotus', 'Elan', 'Gabon');
insert into coches (id, marca, modelo, pais) values (708, 'Ford', 'Crown Victoria', 'Syria');
insert into coches (id, marca, modelo, pais) values (709, 'BMW', 'Z4 M', 'China');
insert into coches (id, marca, modelo, pais) values (710, 'Subaru', 'Forester', 'Greece');
insert into coches (id, marca, modelo, pais) values (711, 'Buick', 'Hearse', 'Russia');
insert into coches (id, marca, modelo, pais) values (712, 'Honda', 'CR-X', 'China');
insert into coches (id, marca, modelo, pais) values (713, 'Hyundai', 'Elantra', 'Argentina');
insert into coches (id, marca, modelo, pais) values (714, 'Mercury', 'Mystique', 'Sweden');
insert into coches (id, marca, modelo, pais) values (715, 'Dodge', 'Viper', 'Argentina');
insert into coches (id, marca, modelo, pais) values (716, 'Honda', 'Civic', 'China');
insert into coches (id, marca, modelo, pais) values (717, 'Acura', 'MDX', 'China');
insert into coches (id, marca, modelo, pais) values (718, 'Toyota', 'Tacoma', 'Honduras');
insert into coches (id, marca, modelo, pais) values (719, 'Dodge', 'Ram 2500 Club', 'Thailand');
insert into coches (id, marca, modelo, pais) values (720, 'GMC', 'Canyon', 'Bulgaria');
insert into coches (id, marca, modelo, pais) values (721, 'Lexus', 'LS', 'France');
insert into coches (id, marca, modelo, pais) values (722, 'Chevrolet', '3500', 'China');
insert into coches (id, marca, modelo, pais) values (723, 'Mazda', 'Millenia', 'China');
insert into coches (id, marca, modelo, pais) values (724, 'Spyker', 'C8 Double 12 S', 'Norway');
insert into coches (id, marca, modelo, pais) values (725, 'Toyota', 'Avalon', 'China');
insert into coches (id, marca, modelo, pais) values (726, 'Chevrolet', 'Volt', 'Malaysia');
insert into coches (id, marca, modelo, pais) values (727, 'Mitsubishi', 'Chariot', 'Curacao');
insert into coches (id, marca, modelo, pais) values (728, 'Audi', 'A8', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (729, 'Infiniti', 'J', 'Philippines');
insert into coches (id, marca, modelo, pais) values (730, 'Volkswagen', 'CC', 'Nigeria');
insert into coches (id, marca, modelo, pais) values (731, 'GMC', 'Envoy XUV', 'United Kingdom');
insert into coches (id, marca, modelo, pais) values (732, 'Lincoln', 'Mark VII', 'China');
insert into coches (id, marca, modelo, pais) values (733, 'Audi', 'Allroad', 'Philippines');
insert into coches (id, marca, modelo, pais) values (734, 'GMC', 'Sierra 3500HD', 'Netherlands');
insert into coches (id, marca, modelo, pais) values (735, 'Scion', 'tC', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (736, 'Volkswagen', 'Jetta', 'Burkina Faso');
insert into coches (id, marca, modelo, pais) values (737, 'Dodge', 'Intrepid', 'Portugal');
insert into coches (id, marca, modelo, pais) values (738, 'Audi', 'S4', 'China');
insert into coches (id, marca, modelo, pais) values (739, 'Infiniti', 'M', 'Russia');
insert into coches (id, marca, modelo, pais) values (740, 'Chevrolet', 'G-Series 1500', 'Guatemala');
insert into coches (id, marca, modelo, pais) values (741, 'Mazda', 'GLC', 'Portugal');
insert into coches (id, marca, modelo, pais) values (742, 'Toyota', 'Celica', 'China');
insert into coches (id, marca, modelo, pais) values (743, 'Toyota', 'Supra', 'Niger');
insert into coches (id, marca, modelo, pais) values (744, 'Mitsubishi', 'Galant', 'Nicaragua');
insert into coches (id, marca, modelo, pais) values (745, 'Mercedes-Benz', '500E', 'Russia');
insert into coches (id, marca, modelo, pais) values (746, 'Chevrolet', 'Cavalier', 'Sweden');
insert into coches (id, marca, modelo, pais) values (747, 'Chevrolet', 'Corvette', 'China');
insert into coches (id, marca, modelo, pais) values (748, 'Pontiac', 'Firebird', 'China');
insert into coches (id, marca, modelo, pais) values (749, 'Chevrolet', '3500', 'Sweden');
insert into coches (id, marca, modelo, pais) values (750, 'Toyota', 'Highlander', 'China');
insert into coches (id, marca, modelo, pais) values (751, 'Lexus', 'LX', 'Peru');
insert into coches (id, marca, modelo, pais) values (752, 'BMW', '3 Series', 'Mexico');
insert into coches (id, marca, modelo, pais) values (753, 'Kia', 'Carens', 'Malaysia');
insert into coches (id, marca, modelo, pais) values (754, 'Subaru', 'Justy', 'Colombia');
insert into coches (id, marca, modelo, pais) values (755, 'GMC', 'Vandura 1500', 'Sweden');
insert into coches (id, marca, modelo, pais) values (756, 'Maybach', '57', 'Netherlands');
insert into coches (id, marca, modelo, pais) values (757, 'Dodge', 'Dakota', 'Panama');
insert into coches (id, marca, modelo, pais) values (758, 'Dodge', 'Magnum', 'Poland');
insert into coches (id, marca, modelo, pais) values (759, 'Porsche', '944', 'Ukraine');
insert into coches (id, marca, modelo, pais) values (760, 'Cadillac', 'SRX', 'Poland');
insert into coches (id, marca, modelo, pais) values (761, 'Ford', 'Club Wagon', 'Brazil');
insert into coches (id, marca, modelo, pais) values (762, 'Ford', 'Mustang', 'Thailand');
insert into coches (id, marca, modelo, pais) values (763, 'Jeep', 'Wrangler', 'France');
insert into coches (id, marca, modelo, pais) values (764, 'Hyundai', 'Santa Fe', 'Poland');
insert into coches (id, marca, modelo, pais) values (765, 'GMC', 'Envoy', 'Norway');
insert into coches (id, marca, modelo, pais) values (766, 'Honda', 'Fit', 'Argentina');
insert into coches (id, marca, modelo, pais) values (767, 'BMW', 'Z3', 'Ireland');
insert into coches (id, marca, modelo, pais) values (768, 'Suzuki', 'SJ', 'Argentina');
insert into coches (id, marca, modelo, pais) values (769, 'Dodge', 'Ram 2500', 'Finland');
insert into coches (id, marca, modelo, pais) values (770, 'Ford', 'E150', 'Sweden');
insert into coches (id, marca, modelo, pais) values (771, 'Volkswagen', 'GTI', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (772, 'GMC', 'Suburban 2500', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (773, 'Subaru', 'Legacy', 'Argentina');
insert into coches (id, marca, modelo, pais) values (774, 'Suzuki', 'Samurai', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (775, 'Ford', 'F350', 'Papua New Guinea');
insert into coches (id, marca, modelo, pais) values (776, 'Dodge', 'Ram 50', 'China');
insert into coches (id, marca, modelo, pais) values (777, 'Lexus', 'RX Hybrid', 'China');
insert into coches (id, marca, modelo, pais) values (778, 'Acura', 'Integra', 'France');
insert into coches (id, marca, modelo, pais) values (779, 'BMW', '3 Series', 'Senegal');
insert into coches (id, marca, modelo, pais) values (780, 'Bentley', 'Continental Flying Spur', 'China');
insert into coches (id, marca, modelo, pais) values (781, 'Volkswagen', 'Passat', 'Luxembourg');
insert into coches (id, marca, modelo, pais) values (782, 'Morgan', 'Aero 8', 'United States');
insert into coches (id, marca, modelo, pais) values (783, 'Nissan', 'Pathfinder', 'Russia');
insert into coches (id, marca, modelo, pais) values (784, 'BMW', '530', 'Brazil');
insert into coches (id, marca, modelo, pais) values (785, 'Toyota', '4Runner', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (786, 'Toyota', 'Land Cruiser', 'Guinea');
insert into coches (id, marca, modelo, pais) values (787, 'Ford', 'Thunderbird', 'Cuba');
insert into coches (id, marca, modelo, pais) values (788, 'Ford', 'Explorer Sport Trac', 'Ukraine');
insert into coches (id, marca, modelo, pais) values (789, 'Suzuki', 'Verona', 'China');
insert into coches (id, marca, modelo, pais) values (790, 'Dodge', 'Ram 2500', 'Japan');
insert into coches (id, marca, modelo, pais) values (791, 'Kia', 'Mohave/Borrego', 'China');
insert into coches (id, marca, modelo, pais) values (792, 'Kia', 'Sedona', 'Russia');
insert into coches (id, marca, modelo, pais) values (793, 'Chevrolet', 'Suburban 2500', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (794, 'Dodge', 'Aspen', 'Czech Republic');
insert into coches (id, marca, modelo, pais) values (795, 'Buick', 'Estate', 'Russia');
insert into coches (id, marca, modelo, pais) values (796, 'Cadillac', 'Seville', 'China');
insert into coches (id, marca, modelo, pais) values (797, 'Chevrolet', 'Corvette', 'Cuba');
insert into coches (id, marca, modelo, pais) values (798, 'Pontiac', 'Bonneville', 'Ukraine');
insert into coches (id, marca, modelo, pais) values (799, 'Ford', 'F150', 'Comoros');
insert into coches (id, marca, modelo, pais) values (800, 'Pontiac', 'Turbo Firefly', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (801, 'Infiniti', 'FX', 'China');
insert into coches (id, marca, modelo, pais) values (802, 'Mercury', 'Cougar', 'China');
insert into coches (id, marca, modelo, pais) values (803, 'Chevrolet', 'G-Series G20', 'Brazil');
insert into coches (id, marca, modelo, pais) values (804, 'Chevrolet', 'HHR', 'Lithuania');
insert into coches (id, marca, modelo, pais) values (805, 'Kia', 'Carens', 'Bulgaria');
insert into coches (id, marca, modelo, pais) values (806, 'Suzuki', 'Sidekick', 'Canada');
insert into coches (id, marca, modelo, pais) values (807, 'Maserati', 'Spyder', 'France');
insert into coches (id, marca, modelo, pais) values (808, 'Audi', 'A6', 'Australia');
insert into coches (id, marca, modelo, pais) values (809, 'Pontiac', '6000', 'Sweden');
insert into coches (id, marca, modelo, pais) values (810, 'Suzuki', 'XL7', 'Sudan');
insert into coches (id, marca, modelo, pais) values (811, 'Saab', '9-5', 'Czech Republic');
insert into coches (id, marca, modelo, pais) values (812, 'Audi', 'S4', 'China');
insert into coches (id, marca, modelo, pais) values (813, 'Volvo', 'S40', 'Paraguay');
insert into coches (id, marca, modelo, pais) values (814, 'Isuzu', 'Rodeo', 'Ukraine');
insert into coches (id, marca, modelo, pais) values (815, 'GMC', 'Savana 1500', 'Philippines');
insert into coches (id, marca, modelo, pais) values (816, 'Volvo', 'V50', 'Sweden');
insert into coches (id, marca, modelo, pais) values (817, 'Lexus', 'ES', 'Philippines');
insert into coches (id, marca, modelo, pais) values (818, 'Plymouth', 'Neon', 'Sweden');
insert into coches (id, marca, modelo, pais) values (819, 'Ford', 'Thunderbird', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (820, 'Jeep', 'Compass', 'Philippines');
insert into coches (id, marca, modelo, pais) values (821, 'Suzuki', 'Swift', 'Venezuela');
insert into coches (id, marca, modelo, pais) values (822, 'Mercedes-Benz', 'S-Class', 'Serbia');
insert into coches (id, marca, modelo, pais) values (823, 'Ford', 'Taurus', 'China');
insert into coches (id, marca, modelo, pais) values (824, 'Chevrolet', 'Tahoe', 'Portugal');
insert into coches (id, marca, modelo, pais) values (825, 'Ford', 'Bronco', 'South Sudan');
insert into coches (id, marca, modelo, pais) values (826, 'Ford', 'F-Series', 'Finland');
insert into coches (id, marca, modelo, pais) values (827, 'GMC', 'Yukon XL 1500', 'Portugal');
insert into coches (id, marca, modelo, pais) values (828, 'BMW', '5 Series', 'Poland');
insert into coches (id, marca, modelo, pais) values (829, 'Ford', 'Excursion', 'Albania');
insert into coches (id, marca, modelo, pais) values (830, 'Mazda', 'MX-5', 'Japan');
insert into coches (id, marca, modelo, pais) values (831, 'BMW', '525', 'Japan');
insert into coches (id, marca, modelo, pais) values (832, 'Infiniti', 'G', 'Brazil');
insert into coches (id, marca, modelo, pais) values (833, 'Cadillac', 'STS-V', 'Brazil');
insert into coches (id, marca, modelo, pais) values (834, 'Kia', 'Sportage', 'Afghanistan');
insert into coches (id, marca, modelo, pais) values (835, 'Mazda', 'Familia', 'Mexico');
insert into coches (id, marca, modelo, pais) values (836, 'Ford', 'LTD', 'Colombia');
insert into coches (id, marca, modelo, pais) values (837, 'Mitsubishi', 'Endeavor', 'Portugal');
insert into coches (id, marca, modelo, pais) values (838, 'Cadillac', 'DeVille', 'Hungary');
insert into coches (id, marca, modelo, pais) values (839, 'GMC', 'Envoy XL', 'Croatia');
insert into coches (id, marca, modelo, pais) values (840, 'Toyota', 'Sienna', 'Thailand');
insert into coches (id, marca, modelo, pais) values (841, 'Nissan', 'Sentra', 'Brazil');
insert into coches (id, marca, modelo, pais) values (842, 'Chevrolet', 'Equinox', 'South Africa');
insert into coches (id, marca, modelo, pais) values (843, 'Chevrolet', 'Silverado', 'Thailand');
insert into coches (id, marca, modelo, pais) values (844, 'Maserati', 'Quattroporte', 'Russia');
insert into coches (id, marca, modelo, pais) values (845, 'BMW', 'Z4', 'China');
insert into coches (id, marca, modelo, pais) values (846, 'Ford', 'Focus ST', 'Japan');
insert into coches (id, marca, modelo, pais) values (847, 'Mitsubishi', 'GTO', 'China');
insert into coches (id, marca, modelo, pais) values (848, 'Chevrolet', 'Express 1500', 'Egypt');
insert into coches (id, marca, modelo, pais) values (849, 'Chrysler', 'Concorde', 'Colombia');
insert into coches (id, marca, modelo, pais) values (850, 'Isuzu', 'Hombre Space', 'Dominican Republic');
insert into coches (id, marca, modelo, pais) values (851, 'Land Rover', 'Freelander', 'Portugal');
insert into coches (id, marca, modelo, pais) values (852, 'Hyundai', 'Azera', 'Philippines');
insert into coches (id, marca, modelo, pais) values (853, 'BMW', '7 Series', 'Serbia');
insert into coches (id, marca, modelo, pais) values (854, 'Nissan', 'Versa', 'Germany');
insert into coches (id, marca, modelo, pais) values (855, 'Plymouth', 'Sundance', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (856, 'Isuzu', 'Rodeo', 'Portugal');
insert into coches (id, marca, modelo, pais) values (857, 'Oldsmobile', '98', 'Nigeria');
insert into coches (id, marca, modelo, pais) values (858, 'GMC', 'Sierra 1500', 'Portugal');
insert into coches (id, marca, modelo, pais) values (859, 'Toyota', 'TundraMax', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (860, 'Spyker', 'C8 Laviolette', 'Uruguay');
insert into coches (id, marca, modelo, pais) values (861, 'Mitsubishi', 'Pajero', 'Yemen');
insert into coches (id, marca, modelo, pais) values (862, 'Nissan', 'Pathfinder', 'Philippines');
insert into coches (id, marca, modelo, pais) values (863, 'Dodge', 'Ram 3500', 'Russia');
insert into coches (id, marca, modelo, pais) values (864, 'Buick', 'Riviera', 'Cambodia');
insert into coches (id, marca, modelo, pais) values (865, 'Dodge', 'Ram Van 3500', 'China');
insert into coches (id, marca, modelo, pais) values (866, 'Cadillac', 'DeVille', 'Finland');
insert into coches (id, marca, modelo, pais) values (867, 'Cadillac', 'Escalade', 'China');
insert into coches (id, marca, modelo, pais) values (868, 'Ford', 'E150', 'Russia');
insert into coches (id, marca, modelo, pais) values (869, 'Mazda', '929', 'Venezuela');
insert into coches (id, marca, modelo, pais) values (870, 'Mitsubishi', 'Lancer Evolution', 'Finland');
insert into coches (id, marca, modelo, pais) values (871, 'Mitsubishi', 'Diamante', 'Bahamas');
insert into coches (id, marca, modelo, pais) values (872, 'Infiniti', 'G37', 'Russia');
insert into coches (id, marca, modelo, pais) values (873, 'Jaguar', 'XJ', 'Denmark');
insert into coches (id, marca, modelo, pais) values (874, 'Toyota', 'Highlander', 'Sweden');
insert into coches (id, marca, modelo, pais) values (875, 'Honda', 'Odyssey', 'Philippines');
insert into coches (id, marca, modelo, pais) values (876, 'Mercury', 'Montego', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (877, 'Volvo', 'XC90', 'Portugal');
insert into coches (id, marca, modelo, pais) values (878, 'Dodge', 'Daytona', 'Poland');
insert into coches (id, marca, modelo, pais) values (879, 'Volkswagen', 'Cabriolet', 'Togo');
insert into coches (id, marca, modelo, pais) values (880, 'Chevrolet', 'Aveo', 'Iraq');
insert into coches (id, marca, modelo, pais) values (881, 'Nissan', 'Frontier', 'Colombia');
insert into coches (id, marca, modelo, pais) values (882, 'Dodge', 'Dakota', 'China');
insert into coches (id, marca, modelo, pais) values (883, 'Jeep', 'Cherokee', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (884, 'Daewoo', 'Lanos', 'Philippines');
insert into coches (id, marca, modelo, pais) values (885, 'Mazda', 'Mazda6', 'Japan');
insert into coches (id, marca, modelo, pais) values (886, 'Mazda', 'Mazdaspeed 3', 'Iran');
insert into coches (id, marca, modelo, pais) values (887, 'Oldsmobile', 'Silhouette', 'Portugal');
insert into coches (id, marca, modelo, pais) values (888, 'Maserati', '430', 'China');
insert into coches (id, marca, modelo, pais) values (889, 'Volkswagen', 'Eurovan', 'Sweden');
insert into coches (id, marca, modelo, pais) values (890, 'Mercedes-Benz', 'S-Class', 'Philippines');
insert into coches (id, marca, modelo, pais) values (891, 'Tesla', 'Roadster', 'Lithuania');
insert into coches (id, marca, modelo, pais) values (892, 'Cadillac', 'CTS', 'China');
insert into coches (id, marca, modelo, pais) values (893, 'Toyota', 'Tacoma', 'Honduras');
insert into coches (id, marca, modelo, pais) values (894, 'Audi', 'Coupe GT', 'Russia');
insert into coches (id, marca, modelo, pais) values (895, 'GMC', 'Sierra Denali', 'China');
insert into coches (id, marca, modelo, pais) values (896, 'Chrysler', 'Pacifica', 'United States');
insert into coches (id, marca, modelo, pais) values (897, 'BMW', 'M5', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (898, 'Dodge', 'Caravan', 'Poland');
insert into coches (id, marca, modelo, pais) values (899, 'Toyota', 'Yaris', 'Japan');
insert into coches (id, marca, modelo, pais) values (900, 'Audi', 'Allroad', 'Sweden');
insert into coches (id, marca, modelo, pais) values (901, 'Lexus', 'LS', 'Cameroon');
insert into coches (id, marca, modelo, pais) values (902, 'Mazda', 'Protege', 'Iran');
insert into coches (id, marca, modelo, pais) values (903, 'BMW', 'Z3', 'Germany');
insert into coches (id, marca, modelo, pais) values (904, 'Chevrolet', 'Express 1500', 'Poland');
insert into coches (id, marca, modelo, pais) values (905, 'Hyundai', 'Azera', 'Luxembourg');
insert into coches (id, marca, modelo, pais) values (906, 'GMC', '1500 Club Coupe', 'Portugal');
insert into coches (id, marca, modelo, pais) values (907, 'Hyundai', 'Equus', 'China');
insert into coches (id, marca, modelo, pais) values (908, 'Buick', 'Century', 'Philippines');
insert into coches (id, marca, modelo, pais) values (909, 'Chevrolet', 'Monte Carlo', 'Tanzania');
insert into coches (id, marca, modelo, pais) values (910, 'GMC', 'Sierra 1500', 'China');
insert into coches (id, marca, modelo, pais) values (911, 'Buick', 'Century', 'Macedonia');
insert into coches (id, marca, modelo, pais) values (912, 'Toyota', '4Runner', 'Nigeria');
insert into coches (id, marca, modelo, pais) values (913, 'GMC', 'Savana 2500', 'Madagascar');
insert into coches (id, marca, modelo, pais) values (914, 'Chrysler', 'Town & Country', 'Peru');
insert into coches (id, marca, modelo, pais) values (915, 'Subaru', 'Legacy', 'Japan');
insert into coches (id, marca, modelo, pais) values (916, 'Suzuki', 'Grand Vitara', 'Philippines');
insert into coches (id, marca, modelo, pais) values (917, 'Suzuki', 'Swift', 'Solomon Islands');
insert into coches (id, marca, modelo, pais) values (918, 'Maserati', 'GranTurismo', 'Cuba');
insert into coches (id, marca, modelo, pais) values (919, 'Lincoln', 'Continental', 'Brazil');
insert into coches (id, marca, modelo, pais) values (920, 'Kia', 'Sephia', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (921, 'Kia', 'Sorento', 'Philippines');
insert into coches (id, marca, modelo, pais) values (922, 'Honda', 'Accord', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (923, 'Ford', 'LTD', 'China');
insert into coches (id, marca, modelo, pais) values (924, 'Mercury', 'Topaz', 'Philippines');
insert into coches (id, marca, modelo, pais) values (925, 'Mazda', 'Mazda5', 'Mauritius');
insert into coches (id, marca, modelo, pais) values (926, 'Chevrolet', 'Aveo', 'Malaysia');
insert into coches (id, marca, modelo, pais) values (927, 'Nissan', 'Titan', 'Hungary');
insert into coches (id, marca, modelo, pais) values (928, 'Chevrolet', 'Tahoe', 'China');
insert into coches (id, marca, modelo, pais) values (929, 'Ford', 'Fusion', 'Thailand');
insert into coches (id, marca, modelo, pais) values (930, 'Mazda', 'Mazdaspeed6', 'China');
insert into coches (id, marca, modelo, pais) values (931, 'Mitsubishi', 'Challenger', 'China');
insert into coches (id, marca, modelo, pais) values (932, 'Mercury', 'Mountaineer', 'Poland');
insert into coches (id, marca, modelo, pais) values (933, 'Ford', 'Thunderbird', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (934, 'Volvo', 'V70', 'Brazil');
insert into coches (id, marca, modelo, pais) values (935, 'Buick', 'LeSabre', 'Argentina');
insert into coches (id, marca, modelo, pais) values (936, 'Mercedes-Benz', '300SL', 'Philippines');
insert into coches (id, marca, modelo, pais) values (937, 'Chrysler', 'Cirrus', 'China');
insert into coches (id, marca, modelo, pais) values (938, 'Ford', 'Expedition EL', 'United States');
insert into coches (id, marca, modelo, pais) values (939, 'Ram', '3500', 'Colombia');
insert into coches (id, marca, modelo, pais) values (940, 'Mercedes-Benz', 'E-Class', 'China');
insert into coches (id, marca, modelo, pais) values (941, 'Acura', 'NSX', 'Russia');
insert into coches (id, marca, modelo, pais) values (942, 'Chevrolet', 'Express 3500', 'Japan');
insert into coches (id, marca, modelo, pais) values (943, 'BMW', 'M3', 'Armenia');
insert into coches (id, marca, modelo, pais) values (944, 'Suzuki', 'Swift', 'China');
insert into coches (id, marca, modelo, pais) values (945, 'GMC', 'Yukon XL 2500', 'China');
insert into coches (id, marca, modelo, pais) values (946, 'Chevrolet', 'Sportvan G20', 'Tunisia');
insert into coches (id, marca, modelo, pais) values (947, 'Toyota', 'Matrix', 'China');
insert into coches (id, marca, modelo, pais) values (948, 'Mazda', 'MX-6', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (949, 'Volkswagen', 'Jetta', 'Russia');
insert into coches (id, marca, modelo, pais) values (950, 'Plymouth', 'Sundance', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (951, 'Suzuki', 'SJ', 'Nigeria');
insert into coches (id, marca, modelo, pais) values (952, 'Subaru', 'Baja', 'Guatemala');
insert into coches (id, marca, modelo, pais) values (953, 'Chevrolet', 'Corvette', 'Croatia');
insert into coches (id, marca, modelo, pais) values (954, 'Ford', 'F350', 'China');
insert into coches (id, marca, modelo, pais) values (955, 'Chevrolet', 'Aveo', 'Portugal');
insert into coches (id, marca, modelo, pais) values (956, 'Porsche', '928', 'Honduras');
insert into coches (id, marca, modelo, pais) values (957, 'Audi', 'Quattro', 'Vietnam');
insert into coches (id, marca, modelo, pais) values (958, 'Mercedes-Benz', 'G-Class', 'Portugal');
insert into coches (id, marca, modelo, pais) values (959, 'Dodge', 'Durango', 'Argentina');
insert into coches (id, marca, modelo, pais) values (960, 'Suzuki', 'Grand Vitara', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (961, 'Infiniti', 'QX56', 'Brazil');
insert into coches (id, marca, modelo, pais) values (962, 'Chevrolet', 'Aveo', 'Brazil');
insert into coches (id, marca, modelo, pais) values (963, 'Hyundai', 'Accent', 'Czech Republic');
insert into coches (id, marca, modelo, pais) values (964, 'Dodge', 'Ram Van 3500', 'Equatorial Guinea');
insert into coches (id, marca, modelo, pais) values (965, 'Ford', 'F450', 'Philippines');
insert into coches (id, marca, modelo, pais) values (966, 'Chevrolet', 'Sportvan G20', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (967, 'Pontiac', 'Grand Am', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (968, 'Toyota', 'Land Cruiser', 'Peru');
insert into coches (id, marca, modelo, pais) values (969, 'Nissan', 'Cube', 'Bangladesh');
insert into coches (id, marca, modelo, pais) values (970, 'Mitsubishi', 'Mirage', 'United States');
insert into coches (id, marca, modelo, pais) values (971, 'Chevrolet', 'Suburban', 'Bosnia and Herzegovina');
insert into coches (id, marca, modelo, pais) values (972, 'GMC', 'Rally Wagon G3500', 'United States');
insert into coches (id, marca, modelo, pais) values (973, 'Oldsmobile', 'Bravada', 'Bosnia and Herzegovina');
insert into coches (id, marca, modelo, pais) values (974, 'Chevrolet', 'HHR', 'Peru');
insert into coches (id, marca, modelo, pais) values (975, 'Chrysler', 'LeBaron', 'Indonesia');
insert into coches (id, marca, modelo, pais) values (976, 'Toyota', 'Tacoma', 'Somalia');
insert into coches (id, marca, modelo, pais) values (977, 'Ford', 'Econoline E250', 'China');
insert into coches (id, marca, modelo, pais) values (978, 'Chevrolet', 'Silverado', 'Philippines');
insert into coches (id, marca, modelo, pais) values (979, 'Subaru', 'Forester', 'China');
insert into coches (id, marca, modelo, pais) values (980, 'Isuzu', 'Hombre Space', 'Ivory Coast');
insert into coches (id, marca, modelo, pais) values (981, 'Chevrolet', 'Express 1500', 'Japan');
insert into coches (id, marca, modelo, pais) values (982, 'Ford', 'C-MAX Hybrid', 'Angola');
insert into coches (id, marca, modelo, pais) values (983, 'Mitsubishi', 'Galant', 'China');
insert into coches (id, marca, modelo, pais) values (984, 'Honda', 'Odyssey', 'China');
insert into coches (id, marca, modelo, pais) values (985, 'Dodge', 'Avenger', 'China');
insert into coches (id, marca, modelo, pais) values (986, 'Oldsmobile', 'Silhouette', 'Comoros');
insert into coches (id, marca, modelo, pais) values (987, 'Subaru', 'Baja', 'Germany');
insert into coches (id, marca, modelo, pais) values (988, 'Hyundai', 'Tucson', 'Jordan');
insert into coches (id, marca, modelo, pais) values (989, 'Mitsubishi', 'Eclipse', 'Hungary');
insert into coches (id, marca, modelo, pais) values (990, 'Chevrolet', 'Corvette', 'Philippines');
insert into coches (id, marca, modelo, pais) values (991, 'Isuzu', 'Stylus', 'Sweden');
insert into coches (id, marca, modelo, pais) values (992, 'Porsche', '928', 'China');
insert into coches (id, marca, modelo, pais) values (993, 'Chevrolet', 'Camaro', 'China');
insert into coches (id, marca, modelo, pais) values (994, 'Hyundai', 'Santa Fe', 'United States');
insert into coches (id, marca, modelo, pais) values (995, 'Lotus', 'Elan', 'Zambia');
insert into coches (id, marca, modelo, pais) values (996, 'Jeep', 'Grand Cherokee', 'Portugal');
insert into coches (id, marca, modelo, pais) values (997, 'Chevrolet', 'Cavalier', 'United States');
insert into coches (id, marca, modelo, pais) values (998, 'Nissan', 'Leaf', 'Ukraine');
insert into coches (id, marca, modelo, pais) values (999, 'Nissan', '300ZX', 'China');
insert into coches (id, marca, modelo, pais) values (1000, 'Mercedes-Benz', 'CL-Class', 'Portugal');
